### ISSUE TITLE
Multi-line variables are not handled

### ISSUE THREAD

**Issue by vanstoner** [xebialabs-community/xlr-addon-for-jira#3]

**Comment by jdewinne** [comment]
What do you mean with multi-line variables? Is that something like

```
${VARNAMEPART1
PART2}
```

**Comment by vanstoner** [comment]
In Jira there are fields that are multi-value fields. With the current addon it seems that those fields can't be used, not even the first line gets copied.  There is of course the design of how to handle such fields in pre-4.8.x XLR but now we have sets and lists we could directly map multilines to those types.  One such usecase is the Environment field where one could list environments for which a ticket is appliccable.

**Comment by jdewinne** [comment]
Get it. Thanks for the explanation.

**Comment by vanstoner** [comment]
Multi-line variables are handled by concatenating the lines into a single string.
